name: ohyeahthat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  flutter_screenutil: ^5.0.0+2
  google_sign_in: ^5.2.3
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^0.6.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5

 #share
  share_plus: ^3.0.4
  share: ^2.0.4
  path_provider: ^2.0.8


  #screenshot
  screenshot: ^1.2.3

  #image saver
  image_gallery_saver: '^1.7.1'
  permission_handler: ^8.3.0
  file: ^6.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts: 
    - family: login
      fonts:
        - asset: font/Jua-Regular.ttf
    - family: main
      fonts:
        - asset : font/DoHyeon-Regular.ttf

 
